spring.application.name=Multi-Vendor-Store

server.port=${PORT:8080}

# --- MySQL Database Configuration ---
spring.datasource.url=jdbc:mysql://mysql-3aca59a5-akhtarbabu7459941478-c7d8.d.aivencloud.com:28794/defaultdb?useSSL=true&enabledTLSProtocols=TLSv1.2,TLSv1.3&trustServerCertificate=true&allowPublicKeyRetrieval=true
spring.datasource.username=avnadmin
spring.datasource.password=${DB_PASSWORD}

# --- JPA / Hibernate Properties ---
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

# Hikari Connection Pool Settings (Reduces 'Communications link failure')
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.idle-timeout=600000
spring.datasource.hikari.max-lifetime=1800000

shop.app.jwtSecret=ThisIsASecretKeyThatIsAtLeast32CharactersLongForHS256Security
#this is token expiration time
shop.app.jwtExpirationMs=86400000
